### ISSUE TITLE
ufw integration on Ubuntu 14.04 doesn't work

### ISSUE THREAD

**Issue by ludovicc** [HanXHX/ansible-firewall#2]
Hello,

I tried to setup fail2ban with ufw on a Ubuntu 14.04 server, but fail2ban could not start as /etc/fail2ban/action.d/ufw.conf did not exist. I remove the when: clause on fail2ban.yml and that worked for me.
On Ubuntu, I have those values for the distribution:
"ansible_distribution": "Ubuntu", 
"ansible_distribution_major_version": "14"

Thanks

**Comment by HanXHX** [comment]
Hi @ludovicc,

I added support of Ubuntu 14 on 162c3c69c21b3743046701ef29326586f8102e4a commit. Can you check it please?

Regards,

Emilien

**Comment by ludovicc** [comment]
The support for Ubuntu 14.04 works, thanks.

Can you tell me why you use le / lt in the comparison ? I would have expected the opposite, the version of Ubuntu or Debian should be greater, and we don't support older versions.

**Comment by HanXHX** [comment]
On older version of fail2ban (debian wheezy), debian package doesn't provide ufw config. With my role, we can manage both cases.
